-- LuxRides cash flow + wallet governance
-- Objetivo:
-- 1) Registrar metodo de pago en reservas/viajes/historial.
-- 2) Llevar wallet virtual del chofer con limite de deuda en efectivo.
-- 3) Exponer funciones SQL para validar si un chofer puede aceptar viajes.

-- Metodo de pago en reservas
alter table if exists public.reservas
  add column if not exists metodo_pago text;

alter table if exists public.reservas
  add column if not exists payment_method text;

alter table if exists public.reservas
  add column if not exists comision_plataforma numeric(12,2);

update public.reservas
set metodo_pago = coalesce(nullif(trim(metodo_pago), ''), nullif(trim(payment_method), ''), 'tarjeta')
where metodo_pago is null or trim(metodo_pago) = '';

update public.reservas
set payment_method = coalesce(nullif(trim(payment_method), ''), nullif(trim(metodo_pago), ''), 'tarjeta')
where payment_method is null or trim(payment_method) = '';

alter table if exists public.reservas
  alter column metodo_pago set default 'tarjeta';

alter table if exists public.reservas
  alter column payment_method set default 'tarjeta';

-- Metodo de pago y liquidacion en viajes
alter table if exists public.viajes
  add column if not exists metodo_pago text;

alter table if exists public.viajes
  add column if not exists payment_method text;

alter table if exists public.viajes
  add column if not exists comision_plataforma numeric(12,2);

alter table if exists public.viajes
  add column if not exists wallet_delta numeric(12,2);

-- Metodo de pago y liquidacion en historial
alter table if exists public.historial
  add column if not exists metodo_pago text;

alter table if exists public.historial
  add column if not exists payment_method text;

alter table if exists public.historial
  add column if not exists comision_plataforma numeric(12,2);

alter table if exists public.historial
  add column if not exists wallet_delta numeric(12,2);

-- Wallet y bloqueo por deuda en choferes
alter table if exists public.choferes
  add column if not exists wallet_balance numeric(12,2);

alter table if exists public.choferes
  add column if not exists cash_debt_limit numeric(12,2) default -300;

alter table if exists public.choferes
  add column if not exists cash_blocked boolean default false;

update public.choferes
set wallet_balance = coalesce(wallet_balance, saldo_disponible, 0)
where wallet_balance is null;

update public.choferes
set cash_debt_limit = coalesce(cash_debt_limit, -300)
where cash_debt_limit is null;

update public.choferes
set cash_blocked = (coalesce(wallet_balance, 0) <= coalesce(cash_debt_limit, -300));

-- Ledger de movimientos de wallet
create table if not exists public.wallet_movements (
  id bigint generated by default as identity primary key,
  chofer_id text not null,
  reserva_id text,
  viaje_id text,
  tipo text not null,
  metodo_pago text,
  amount numeric(12,2) not null,
  comision_plataforma numeric(12,2),
  wallet_balance_before numeric(12,2),
  wallet_balance_after numeric(12,2),
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists wallet_movements_chofer_created_idx
  on public.wallet_movements (chofer_id, created_at desc);

create index if not exists wallet_movements_metodo_idx
  on public.wallet_movements (metodo_pago);

-- Trigger: recalcula bloqueo cuando cambia wallet/limite
create or replace function public.apply_cash_wallet_block()
returns trigger
language plpgsql
as $$
begin
  new.wallet_balance := coalesce(new.wallet_balance, 0);
  new.cash_debt_limit := coalesce(new.cash_debt_limit, -300);
  new.cash_blocked := (new.wallet_balance <= new.cash_debt_limit);
  return new;
end;
$$;

drop trigger if exists trg_apply_cash_wallet_block on public.choferes;
create trigger trg_apply_cash_wallet_block
before insert or update of wallet_balance, cash_debt_limit
on public.choferes
for each row
execute function public.apply_cash_wallet_block();

-- Funcion de validacion para aceptar viajes
create or replace function public.can_driver_accept_trip(p_chofer_id text)
returns table (
  allowed boolean,
  reason text,
  wallet_balance numeric,
  debt_limit numeric,
  cash_blocked boolean
)
language plpgsql
as $$
declare
  v_wallet numeric;
  v_limit numeric;
  v_blocked boolean;
begin
  select
    coalesce(c.wallet_balance, c.saldo_disponible, 0),
    coalesce(c.cash_debt_limit, -300),
    coalesce(c.cash_blocked, false)
  into v_wallet, v_limit, v_blocked
  from public.choferes c
  where c.id = p_chofer_id
  limit 1;

  if not found then
    return query select false, 'CHOFER_NOT_FOUND', null::numeric, null::numeric, null::boolean;
    return;
  end if;

  if v_blocked or v_wallet <= v_limit then
    return query select false, 'DEBT_LIMIT_EXCEEDED', v_wallet, v_limit, true;
    return;
  end if;

  return query select true, 'OK', v_wallet, v_limit, false;
end;
$$;

-- Vista de apoyo para SES (backoffice)
create or replace view public.v_chofer_wallet_resumen as
select
  c.id as chofer_id,
  c.nombre,
  coalesce(c.wallet_balance, c.saldo_disponible, 0)::numeric(12,2) as wallet_balance,
  coalesce(c.cash_debt_limit, -300)::numeric(12,2) as cash_debt_limit,
  coalesce(c.cash_blocked, false) as cash_blocked,
  coalesce(sum(case when wm.metodo_pago = 'efectivo' then wm.amount else 0 end), 0)::numeric(12,2) as neto_efectivo_wallet,
  coalesce(sum(case when wm.metodo_pago = 'efectivo' and wm.amount < 0 then abs(wm.amount) else 0 end), 0)::numeric(12,2) as deuda_por_efectivo,
  coalesce(sum(case when wm.metodo_pago = 'efectivo' and wm.amount > 0 then wm.amount else 0 end), 0)::numeric(12,2) as abonos_efectivo
from public.choferes c
left join public.wallet_movements wm on wm.chofer_id = c.id
group by c.id, c.nombre, c.wallet_balance, c.saldo_disponible, c.cash_debt_limit, c.cash_blocked;

-- Consultas utiles para auditoria financiera (SES):
-- 1) Choferes bloqueados por deuda de efectivo:
--    select * from public.v_chofer_wallet_resumen where cash_blocked = true order by wallet_balance asc;
-- 2) Movimientos de wallet de un chofer:
--    select * from public.wallet_movements where chofer_id = 'CHOFER_ID' order by created_at desc;
-- 3) Total cobrado en efectivo por chofer (historial):
--    select chofer_id, sum(precio) as total_efectivo
--    from public.historial
--    where coalesce(metodo_pago, payment_method) = 'efectivo'
--    group by chofer_id
--    order by total_efectivo desc;
